#数据源相关信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cithub-users
#    url: jdbc:mysql://210.28.135.32:9100/cithub-users
    driver-class-name: com.mysql.cj.jdbc.Driver

  #    nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        server-addr: 210.28.135.32:8848


  #       注册到nacos注册中心的名字
  application:
    name: cithub-users

#      本服务运行端口
server:
  port: 9034
